### ISSUE TITLE
minChars and multiple words

### ISSUE THREAD

**Issue by vierkantemeter** [Coroico/AdvSearch#59] opened 2013-11-25 09:42 UTC
If you search for multiple words (like a sentence) and one of those words is shorter than minChars setting, the minChars error is displayed. For me it would be more logical if this setting calculates the total characters used, not per word. 

For example, if I search for:

'a place to stay' I would get the error because 'a' and 'to' are too short.

**Comment by vierkantemeter** [comment] 2013-11-25 09:47
besides that, when I add &minChars=`1` to the advSearch snippet call, it doesn't seem to work, still defaults to 3.

Edit: I figured the problem with adding minChars=`1`. The script defaults to '3' if the entered value is lower than 2, so for this to work for 2 characters you have to add minChars=`2`.

**Comment by goldsky** [comment] 2013-12-15 04:46
this is going to be valid for chinese language, but searching 'a' and 'to' seems going to break your server if it returns all of the web's contents, don't you think?

**Comment by vierkantemeter** [comment] 2013-12-16 08:12
Yeah, you're right about that, but still some of my clients now complain that some important pages on their site can't be found. They search for a sentence, like 'a place to stay' (but without quotes) and no results are shown, only the error that it's not enough characters. I imagine other site visitors will search the same way. 

Maybe it would be better if it worked like this:
a) when the search consists of one word with < 3 characters, show the error
b) when the search consists of multiple words of which only some are too short, disregard the short words and only search for the longer words. This way, when a user searches for 'a place to stay', the search only uses 'place' and 'stay' and the expected result will probably be found anyway. 

To me that would be more intuitive than showing the error even if there are longer words in the search phrase as well. What do you think of this approach?

**Comment by goldsky** [comment] 2013-12-24 07:04
Looks like I found where the problem is.
This will be improved as well on [DB optimization](https://github.com/Coroico/AdvSearch/issues/66)

**Comment by vierkantemeter** [comment] 2013-12-24 09:40
Great news, thanks!

**Comment by goldsky** [comment] 2014-03-06 00:28
this has been fixed on the upcoming update.

**Closed as completed by goldsky** 2014-03-06 00:28 UTC
